openapi: 3.0.3

info:
  title: Geek Camp API 
  description: 技育キャンプハッカソンのAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:80/api
    description: "ローカル環境"

tags: 
  - name: places
    description: 場所に関するAPI

paths:
#=================== places ======================#
  /places:
    get:
      summary: place一覧を取得
      tags:
        - places
      deprecated: false
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/place'
        400:
          description: Invalid status value
          content: {}

    post:
      summary: placeを作成
      tags:
        - places
      deprecated: false
      requestBody:
        description: 作成するplace情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "三重県に旅行行く"
                status_id:
                  type: integer
                  example: 0
                  description: "0:未着手, 1:予定割り当て済み, 2:達成済" 
                tag_id:
                  type: integer
                  example: 1
                address:
                  type: string
                  example: "三重県伊勢市宇治館町１"
                date:
                  type: string
                  example: '2023-10-13'
                  format: date

      responses:
        201:
          description: "成功"
        400:
          description: Invalid status value
          content: {}

  /places/{id}:
    put:
      summary: 指定したIDのplaceを更新
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: place_id
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 更新するplace情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "三重県に旅行行く"
                status_id:
                  type: integer
                  example: 0
                  description: "0:未着手, 1:予定割り当て済み, 2:達成済" 
                tag_id:
                  type: integer
                  example: 1
                address:
                  type: string
                  example: "三重県伊勢市宇治館町１"
                date:
                  type: string
                  example: '2023-10-13'
                  format: date
      responses:
        200:
          description: "成功"
        400:
          description: Invalid status value
          content: {}

    delete:
      summary: 指定したIDのplaceを削除
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: place_id
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: 'No Content'
        '404':
          description: 'Not Found'

  /places/{tag_id}:
    get:
      summary: 指定したタグIDのplaceを取得
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: tag_id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/place'
        400:
          description: Invalid status value
          content: {}

  /places/{id}/status/{status_id}:
    patch:
      summary: placeステータスを更新
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: place_id
          required: true
          schema:
            type: integer
          example: 1
        - name: status_id
          in: path
          description: status_id
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 更新するステータス情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status_id:
                  type: integer
                  example: 2
      responses:
        200:
          description: "成功"
        400:
          description: Invalid status value
          content: {}


components:
  schemas:
    place:
      type: object
      properties:
        id:
          type: integer
          example: 1
        content:
          type: string
          example: "三重県に旅行行く"
        status_id:
          type: integer
          example: 0
          description: "0:未着手, 1:予定割り当て済み, 2:達成済" 
        tag_id:
          type: array
          items:
            $ref: '#/components/schemas/tags'
        address:
          type: string
          example: "三重県伊勢市宇治館町１"
        date:
          type: string
          example: '2023-10-13'
          format: date

    tags:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "一人旅"
        color:
          type: string
          example: "#FF0000"
