openapi: 3.0.3

info:
  title: Geek Camp API 
  description: 技育キャンプハッカソンのAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:80/api
    description: "ローカル環境"

tags: 
  - name: places
    description: 場所に関するAPI

paths:
#=================== places ======================#
  /places:
    get:
      summary: place一覧を取得
      tags:
        - places
      deprecated: false
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/place'
        400:
          description: Invalid status value
          content: {}

    post:
      summary: placeを作成
      tags:
        - places
      deprecated: false
      requestBody:
        description: 作成するplace情報
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/place' 

      responses:
        201:
          description: "成功"
        400:
          description: Invalid status value
          content: {}

  /places/{tag_id}:
    get:
      summary: 指定したタグIDのplaceを取得
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: tag_id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/place'
        400:
          description: Invalid status value
          content: {}

  /places/{id}/status/{status_id}:
    patch:
      summary: placeステータスを更新
      tags:
        - places
      deprecated: false
      parameters:
        - name: id
          in: path
          description: place_id
          required: true
          schema:
            type: integer
          example: 1
        - name: status_id
          in: path
          description: status_id
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 更新するステータス情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status_id:
                  type: integer
                  example: 2
      responses:
        200:
          description: "成功"
        400:
          description: Invalid status value
          content: {}

#=================== groups ======================#
  /groups:
    get:
      summary: group一覧を取得
      tags:
        - groups
      deprecated: false
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/group'
        400:
          description: Invalid status value
          content: {}
      
    post:
      summary: グループを作成
      tags:
        - groups
      deprecated: false
      requestBody:
        description: 作成するグループ情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "学科の友達！"
                color:
                  type: string
                  example: "#FF0000"
                email:
                  type: array
                  example: ["fskf@gmail.com", "fdsffg@gmail.com"] 

      responses:
        201:
          description: "成功"
        400:
          description: Invalid status value
          content: {}


  /groups/{group_id}:
    get:
      summary: 指定したグループIDのグループを取得
      tags:
        - groups
      deprecated: false
      parameters:
        - name: group_id
          in: path
          description: group_id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "成功"
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/group'
        400:
          description: Invalid status value
          content: {}

    put:
      summary: 指定したIDのgroupを更新
      tags:
        - groups
      deprecated: false
      parameters:
        - name: id
          in: path
          description: group_id
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        description: 更新するgroup情報
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/group'
      responses:
        200:
          description: "成功"
        400:
          description: Invalid status value
          content: {}

    delete:
      summary: 指定したIDのgroupを削除
      tags:
        - groups
      deprecated: false
      parameters:
        - name: id
          in: path
          description: group_id
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: 'No Content'
        '404':
          description: 'Not Found'

components:
  schemas:
    place:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "三重県に旅行行く"
        status:
          type: integer
          example: 0
          description: "0:未着手, 1:予定割り当て済み, 2:達成済" 
        tag_id:
          type: integer
          example: 1
        latitude:
          type: number
          format: double
          description: 緯度
          example: 34.686555
        longitude:
          type: number
          format: double
          description: 経度
          example: 141.350784
        date:
          type: array
          example: ['2023-10-13', '2023-10-16']
          format: date

    group:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "一人旅"
        color:
          type: string
          example: "#FF0000"
    
    member:
      type: object
      properties:
        id:
          type: integer
          example: 1
        group_id:
          type: integer
          example: 1
        email:
          type: string
          example: "sdfk@gmail.com"
